---
title: 'Milestone #2'
author: "Buddy Scott"
date: "9/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Project 1: https://ryangraff14.shinyapps.io/milestone8/ 

# I think this project has great intentions and attempts to answer a question
# that a lot of basketball fans constantly wonder: Who won the trade? However,
# there are a few immediate flaws I noticed. First, the arbitrary nature of the
# starting year and the few statistics in which the model is based inevitably
# is flawed. For example, the model looks at three-point shooting percentage, 
# but does not take into account the volume with which three pointers were 
# taken, if the player is great but does not attempt threes, or control for the 
# recent uptick in three point shooting in the last decade or so. Secondly, it 
# does not do a good job attempting to be more applicable to broader data 
# science and admittedly seems to only appeal to die-hard basketball fans like 
# myself. Also, the project does not explain how these complicated advanced 
# stats such as VORP and BPM are calculated. Lastly, the video could have been 
# a lot more professional, like using a screen record instead of holding a 
# camera towards his computer.
```

```{r}
# Project 2: https://hamaadwmehal.shinyapps.io/fp_ms_6_shiny/

# This project also dealt with NBA questions, this time about the relationship
# between fines and player salaries. Unlike the previous project, it simply
# presented some correlation-type plots over the last couple of years and its 
# conclusion has severe causal limitations. The first constructive criticism 
# I have is that a lot of the graphs have roughly 95% of the data points in 
# the bottom fourth of the graph but the y-axis is very stretched out because 
# of a few outlier points. He should be done log salary instead of salary for
# the x and y axes! Second, I think the project needed to have a narrower
# focus. I think it would have been cool to see a breakdown of the different
# reasons for fines. Did the player talk inappropriately to a referee, get into
# a fight, make a out-of-line postgame comment? Simply using fine amount and
# the number of fines leaves a lot to be desired. Lastly, the tab with the 
# regression outputs could have had further explanations than just a simple
# output table. I want to know what this regression output means, why he ran 
# the regression, etc.

```

# Link to repository: https://github.com/buddyscott/milestone-2

